feat(dhcp): client identifier option
lwip-tcpip/lwip pull request #10
Opened 2022-02-21 12:28 UTC by vulptex

Add DHCP option 61. This is used by a lot of DHCP servers in enterprise environment to determine the correctness of the client (whitelisting).

2022-02-21 12:29 UTC, vulptex commented
@yarrick ;-)

2022-03-03 21:10 UTC, yarrick requested changes
Please remove the `feat()` part of the commit title, and add a description what is used as identifier (the RFC allows any data)

2022-03-03 21:10 UTC, yarrick commented on src/core/ipv4/dhcp.c
> +#if LWIP_NETIF_HOSTNAME
Suggest to move this change (sending hostname in discover) to a separate commit

2022-03-03 21:10 UTC, yarrick commented on src/core/ipv4/dhcp.c
> +    options_out_len = dhcp_option_client_identifier(options_out_len, msg_out->options, netif);
Indent looks wrong

2022-03-03 21:10 UTC, yarrick commented on src/core/ipv4/dhcp.c
> +  options_out_len = dhcp_option(options_out_len, options, DHCP_OPTION_CLIENT_ID, DHCP_OPTION_CLIENT_ID_MAC_LEN);
Since dynamic length is used later (netif->hwaddr_len) it seems wrong to have a constant here

2022-03-03 21:10 UTC, yarrick commented on src/core/ipv4/dhcp.c
> +  options_out_len = dhcp_option_byte(options_out_len, options, DHCP_OPTION_CLIENT_ID_MAC);
We already have `LWIP_IANA_HWTYPE_ETHERNET` defined

2022-03-03 21:10 UTC, yarrick commented on src/include/lwip/opt.h
> +#define LWIP_DHCP_OPTION_CLIENT_IDENTIFIER      0
Maybe call it `LWIP_DHCP_SEND_CLIENT_IDENTIFIER` or similar, the other flags controlling options dont include option in their name

2022-03-03 21:10 UTC, yarrick commented on src/include/lwip/prot/dhcp.h
> +#if LWIP_DHCP_OPTION_CLIENT_IDENTIFIER
No need for #if here with the two new constants gone

2022-03-03 21:10 UTC, yarrick commented on src/include/lwip/prot/dhcp.h
> +
Remove

2022-03-28 06:50 UTC, vulptex commented
Lets close this for now.I need more free-time todo it properly.

2022-03-28 06:50 UTC, closed without merging