snmp: fix dangling pointer in snmp_traps
lwip-tcpip/lwip pull request #51
Opened 2024-11-01 09:51 UTC by j123b567

fixes: https://savannah.nongnu.org/bugs/?64685
fixes: https://savannah.nongnu.org/bugs/?64847
replaces: https://github.com/lwip-tcpip/lwip/pull/42 which is wrong

2024-11-27 09:08 UTC, j123b567 commented
This function is a trap :( 

This is not a real dangling pointer, because it is fixed afterwards, but the compiler is not smart enough to see it.
```c
original_varbinds->prev = original_prev;
```
And I understand, because the code is terrible.

There is a much bigger problem with the SNMP code. `snmp_varbind` is defined with `prev` but it is never used in any part of SNMP. Only the snmp_trap code tries to set it correctly, but all traversal functions use only `next`.

Is it ok for you to remove all `prev` handling to prevent this situation?

This function had two dangling pointers. One was real and is fixed by the first commit, the second was false positive and is fixed by the second commit.

2024-11-27 23:06 UTC, yarrick commented
Can you remove the prev pointer in `struct snmp_varbind` also to make sure it isn't used?

2024-11-27 23:43 UTC, yarrick requested changes
Can you remove the `prev` pointer in `struct snmp_varbind` also to make sure it isn't used?

2024-11-29 10:57 UTC, j123b567 commented
Sure.

I thing, that it is breaking change for user applications. Nobody is probably using `prev` field but everybody is setting it to `NULL` during initialization of `snmp_varbind`.

2024-11-29 12:31 UTC, j123b567 commented
Should I also add something like this to `UPGRADING`?

```
  * The prev field in the snmp_varbind structure has been removed.
```

2024-11-29 17:25 UTC, yarrick approved these changes

2024-11-29 17:25 UTC, yarrick commented
I can add it for you.

2024-11-29 17:26 UTC, merged